# Keep NewPipe Extractor classes needed for YouTube extraction
-keep class org.schabi.newpipe.extractor.** { *; }
-keep class org.mozilla.javascript.** { *; }
-keep class org.mozilla.javascript.engine.** { *; }

# Rhino's JS bytecode compiler (used at runtime for JS optimization)
-keep class org.mozilla.classfile.ClassFileWriter

# Keep downloader classes
-keep class org.schabi.newpipe.extractor.downloader.** { *; }
-keep class org.schabi.newpipe.extractor.downloader.Request { *; }
-keep class org.schabi.newpipe.extractor.downloader.Response { *; }

# Don't obfuscate NewPipe classes
-keepnames class org.schabi.newpipe.** { *; }

# ------------------------------------------------------------------
# Rhino (org.mozilla.javascript, pulled in by NewPipe Extractor)
# references desktop-JDK-only classes that DO NOT exist on Android:
#   java.beans.*, javax.script.*, jdk.dynalink.*
# These cannot be bundled into the APK (they are not part of the
# Android runtime). `-keep` on them FAILS the R8 build; the correct
# directive is `-dontwarn`, which tells R8 to ignore the missing
# references (Rhino's core JS engine does not need them at runtime).
# Rules generated by R8 (see build/app/outputs/mapping/release/missing_rules.txt).
-dontwarn java.beans.BeanDescriptor
-dontwarn java.beans.BeanInfo
-dontwarn java.beans.IntrospectionException
-dontwarn java.beans.Introspector
-dontwarn java.beans.PropertyDescriptor
-dontwarn javax.script.AbstractScriptEngine
-dontwarn javax.script.Bindings
-dontwarn javax.script.Compilable
-dontwarn javax.script.CompiledScript
-dontwarn javax.script.Invocable
-dontwarn javax.script.ScriptContext
-dontwarn javax.script.ScriptEngine
-dontwarn javax.script.ScriptEngineFactory
-dontwarn javax.script.ScriptException
-dontwarn javax.script.SimpleBindings
-dontwarn jdk.dynalink.CallSiteDescriptor
-dontwarn jdk.dynalink.DynamicLinker
-dontwarn jdk.dynalink.DynamicLinkerFactory
-dontwarn jdk.dynalink.NamedOperation
-dontwarn jdk.dynalink.Namespace
-dontwarn jdk.dynalink.NamespaceOperation
-dontwarn jdk.dynalink.Operation
-dontwarn jdk.dynalink.RelinkableCallSite
-dontwarn jdk.dynalink.StandardNamespace
-dontwarn jdk.dynalink.StandardOperation
-dontwarn jdk.dynalink.linker.GuardedInvocation
-dontwarn jdk.dynalink.linker.GuardingDynamicLinker
-dontwarn jdk.dynalink.linker.LinkRequest
-dontwarn jdk.dynalink.linker.LinkerServices
-dontwarn jdk.dynalink.linker.TypeBasedGuardingDynamicLinker
-dontwarn jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker
-dontwarn jdk.dynalink.linker.support.Guards
-dontwarn jdk.dynalink.support.ChainedCallSite
